name = "coin-tracker"
compatibility_date = "2024-03-30"

[[d1_databases]]
binding = "DB"
database_name = "coin"
database_id = "4c32ba78-84f7-49bc-828b-23705e3fd163"
account_id = "3089f656c1f39b1156a4007b0a9d9fdd"
